name: AOC_develop
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  # Core language
  - python=3.11

  # Workflow engine
  - snakemake=9.14.5

  # Bioinformatics
  - hyphy=2.5.86
  #- mafft=7.520
  - macse=2.07
  - biopython
  - seqkit
  - iqtree=3.0.1
  - tn93=1.0.15

  # Data handling
  - pandas
  - numpy

  # Utilities
  - pyyaml
  - click
  - tqdm
  - pip
  - ete3=3.1.2
  - matplotlib=3.10.8

  # Optional QoL
  - ripgrep
  - tree
